services:
  dbt:
    build: .
    volumes:
      - .:/usr/app
      # On lie directement le fichier au lieu du dossier
      - ./profiles.yml:/root/.dbt/profiles.yml
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/app/credentials.json