services:
  extract:
    build: .
    entrypoint: ["python", "scripts/extract_transfers.py"]
    volumes:
      - .:/usr/app
    env_file:
      - .env

  dbt:
    build: .
    volumes:
      - .:/usr/app
      - ./profiles.yml:/root/.dbt/profiles.yml
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/app/credentials.json